import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from 'next-auth/client'

export default function BasicAuth() {
  console.log(useSession())
  const [ session, loading ] = useSession()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome Ram Sowmya</h1>
      {
        !session && <>
        Please Sign In to continue
        <button onClick={() => signIn()}>SignIn</button>
        </>
      }
      {
        session && <>
        Welcome {session.user.name} !!
        
        <button onClick={() => signOut()}>SignOut</button>
        </>
      }

    </div>
  )
}


